### ISSUE TITLE
Error: Cannot find module 'graceful-fs'

### ISSUE THREAD

**Issue by ElijahLynn** [NV/chrome-devtools-autosave-server#28]
Ubuntu 12.04

sudo npm install -g autosave

module.js:340
    throw err;
          ^
Error: Cannot find module 'graceful-fs'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/usr/share/npm/lib/utils/ini.js:32:10)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)

**Comment by ElijahLynn** [comment]
http://stackoverflow.com/questions/10776405/npm-cant-install-appjs-error-cannot-find-module-graceful-fs

sudo apt-get remove npm
sudo apt-get install npm
